application: the-marketing-stall
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: site/static/

- url: /
  static_files: site/index.html
  upload: site/index.html

skip_files:
- ^(.*/)?app.yaml
- ^(.*/)?app.yml
- ^(.*/)?index.yaml
- ^(.*/)?index.yml
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- tmp
- node_modules
